DROP TABLE IF EXISTS db_1712.BaiduMap;
CREATE TABLE db_1712.BaiduMap(
  id int AUTO_INCREMENT PRIMARY KEY COMMENT 'ID PK',
  loc VARCHAR(255) COMMENT '地理位置',
  geo VARCHAR(255) COMMENT '经纬度'
)COMMENT '城市经纬度';

SELECT *
FROM db_1712.BaiduMap;

DELETE FROM db_1712.BaiduMap;